steps:
#copy the website content to a GS bucket
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: Sync the content
  args: ['gsutil', '-m', 'rsync', '-d', '-r', 'resume-blog/','gs://cloud-resume-website-bucket']
logsBucket: 'gs://build-log-bucket'
options:
  logging: GCS_ONLY
