steps:
#copy the website content to a GS bucket
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: Sync the content
  args: ['gsutil', '-m', 'rsync', '-d', '-r', 'resume-blog/','gs://cloud-resume-website-bucket']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: Invalidate the content CDN
  args: ['gcloud', 'compute', 'url-maps', 'invalidate-cdn-cache', 'cloudresume-url-map', '--path', '/*', '--project', '$PROJECT_ID']

serviceAccount: '218055873640@cloudbuild.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY
